/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFBX } from "@react-three/drei";
import { startTransition, Suspense, useRef } from "react";
import { Point2D } from "../../../data/point.type";

const Terrain3D = ({
	setPoint,
	currentTarget,
}: {
	setPoint: (point: Point2D) => void;
	currentTarget?: Point2D;
}) => {
	const groupRef = useRef();
	const terrain = useFBX("/models/MarsYard2024.fbx");

	return (
		<group
			ref={groupRef}
			dispose={null}
			scale={0.01}
			rotation={[0, Math.PI / 2, 0]}
			position={[0, -0.47, 0]}
			onClick={(e) => {
				if (e.delta < 2)
					startTransition(() => {
						setPoint({ x: e.point.x, y: e.point.z });
					});
			}}
			onPointerUp={(e) => {
				// check right click
				if (e.button === 2 && e.delta < 2 && currentTarget) {
					startTransition(() => {
						setPoint(currentTarget);
					});
				}
			}}
		>
			<primitive object={terrain} />
		</group>
	);
};

//useFBX.preload("/models/MarsYard2024.glb");

export default Terrain3D;
