on:
    push:
        branches: [main]

jobs:
    build:
        name: create-package
        runs-on: ubuntu-latest

        permissions:
            contents: write

        strategy:
            matrix:
                node-version: [16]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              name: Use Node.js 16
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci

            - run: npm run build --if-present
              env:
                  CI: false
            - run: ls
            - name: Copy to another repo
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
              with:
                  user-name: ${{ github.actor }}
                  source-directory: "./build"
                  target-directory: "./cs_ws/src/control_station_pkg/control_station_pkg/csApp/frontend/build"
                  destination-github-username: "EPFLXplore"
                  destination-repository-name: "ERC_CS_ControlStation"
                  commit-message: See ORIGIN_COMMIT from $GITHUB_REF
                  target-branch: main
                  create-target-branch-if-needed: true
