on:
    push:
        branches: [main]

jobs:
    build:
        name: create-package
        runs-on: ubuntu-latest

        permissions:
            contents: read

        strategy:
            matrix:
                node-version: [16]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              name: Use Node.js 16
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci

            - run: npm run build --if-present
              env:
                  CI: false
            - run: ls
            - name: Copy to another repo
              uses: nkoppel/push-files-to-another-repository@v1.1.2
              env:
                  API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
              with:
                  source-files: "./build"
                  destination-directory: "./cs_ws/src/control_station_pkg/control_station_pkg/csApp/frontend/build"
                  destination-username: "EPFLXplore"
                  destination-repository: "ERC_CS_ControlStation"
