on:
    push:
        branches: [main]

jobs:
    build:
        name: create-package
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              name: Use Node.js 16
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci

            - run: npm run build --if-present
              env:
                  CI: false
            - run: ls
            - name: Copy to another repo
              uses: andstor/copycat-action@v3
              with:
                  personal_token: ${{ secrets.API_TOKEN_GITHUB_SERVER }}
                  src_path: build
                  dst_path: ./cs_ws/src/control_station_pkg/control_station_pkg/csApp/frontend/build
                  dst_owner: TheGuyWithoutH
                  dst_repo_name: ERC_CS_ControlStation
                  dst_branch: main
